sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t vicky048/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vicky048/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-rec"
  env: "DockerRec-env"
  bucket_name: "elasticbeanstalk-ca-central-1-136905702875"
  bucket_path: "docker-rec"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY