sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t vicky048/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vicky048/docker-react npm run test